### ISSUE TITLE
Is this exclusively for imgur?

### ISSUE THREAD

**Issue by mayuso** [DiSiqueira/DSDownload#1]
I saw all examples use imgur, can I use these scripts to download from other sites or is it only for image downloads from imgur?

**Comment by d6o** [comment]
You can download files from everywhere. I'll update examples. 

``` bash
$ dsdownload https://github.com/DiSiqueira/DSDownload/archive/1.4.0.1.zip
```

Thanks for the feedback

**Comment by mayuso** [comment]
Many thanks! This project suddenly became really interesting to me :)
