### ISSUE TITLE
Module Usage->example error

### ISSUE THREAD

**Issue by wudenggang** [DiSiqueira/DSDownload#10]
Win7 Python3.5  
Module Usage->example:
`DSDownload(urls,` workers, `output)` should be `DSDownload.DSDownload(urls,` workers, `output)`
Or
 Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\TEST.PY", line 12, in <module>
    DSDownload(urls, workers,output)
TypeError: 'module' object is not callable

**Comment by d6o** [comment]
Fixed!

Thank you!
