### ISSUE TITLE
"Fastest Speeds Possible" Is Entirely Misleading

### ISSUE THREAD

**Issue by zQueal** [DiSiqueira/DSDownload#5]
To confirm my suspicions I installed `dsdownload` and tested it against Aria2 using a super simple CLI timer.
## DSDownload

```
λ timer dsdownload http://wiki.alpinelinux.org/cgi-bin/dl.cgi/v3.3/releases/x86_64/alpine-3.3.1-x86_64.iso
[Worker 1] Downloading alpine-3.3.1-x86_64.iso
All files were downloaded.

Start: 21:34:09.76
End:   21:36:18.41
```

Total Time: 02:09.35 @ 0.6357 MB/s
## Aria2

```
λ timer aria2c -x5 http://wiki.alpinelinux.org/cgi-bin/dl.cgi/v3.3/releases/x86_64/alpine-3.3.1-x86_64.iso

01/27 21:38:52 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.
[#bbc5d1 80MiB/82MiB(98%) CN:1 DL:5.6MiB]
01/27 21:39:07 [NOTICE] Download complete: D://alpine-3.3.1-x86_64.iso

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
bbc5d1|OK  |   5.6MiB/s|D://alpine-3.3.1-x86_64.iso

Status Legend:
(OK):download completed.

Start: 21:38:51.79
End:   21:39:07.17
```

Total Time: 00:56.62 @ 5.6MB/s

---

There seems to be considerable overhead when using your library vs any other mature download manager. I believe it's entirely misleading to advertise it as 400% faster when I could have downloaded this normally via browser faster than pulling it with 5 threads via Python let alone 8.8 times faster using Aria2.

This isn't a slam piece, I realize the potential when used programmatically, but I still think it's misleading.

**Comment by leokhachatorians** [comment]
Entirely true, honestly, downloading one file shouldn't need to run multiple threads. This would be better served with large amount of file downloads.

**Comment by zQueal** [comment]
Well, like I said, this isn't meant to be a slam ticket. I've already implemented this toolset into 4 of my other projects already, so it's entirely useful. I just don't see the benefit of advertising it like a download manager.

**Comment by d6o** [comment]
I understand your position, to arrive at this number I compared the download time of 10 files (~ 1MB each) using a single thread (That's what I call regular download) and using the DSDownload with 10 threads.

I hope that one day the DSDownload can really be compared with software such as Aria2

Tomorrow will push a new version (probably 2.0.0.0) and I'll rewrite the entire ReadMe removing all the hype and focusing on what really matters.

Thank you all for your feedback.

**Comment by zQueal** [comment]
Hey, awesome! I look forward to testing it. It really is a great library. :)

**Comment by d6o** [comment]
Advertising removed with the launch of the new version 1.6.0.0

**Comment by zQueal** [comment]
Thanks for doing this! I know it was a pretty unreasonable request -- but I believe you would have hit that issue sooner or later. 1.6.0 is tested and working fabulously.

**Comment by d6o** [comment]
Thank you for feedback @zQueal !
Any idea or suggestion do not hesitate to send me, I'll be glad to receive it.
