### ISSUE TITLE
ImportError: No module named 'downloadthread'

### ISSUE THREAD

**Issue by valsaven** [DiSiqueira/DSDownload#6]
Windows 10, Python 3.5.

<pre><code>Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\dsdownload.exe\__main__.py", line 5, in <module>
  File "c:\python35\lib\site-packages\DSDownload\__init__.py", line 11, in <module>
    from DSDownload import DSDownload
  File "c:\python35\lib\site-packages\DSDownload\DSDownload.py", line 15, in <module>
    import downloadthread
ImportError: No module named 'downloadthread'
</code></pre>

In 1.4.1.0 all was fine.

**Comment by inferillum** [comment]
I'm getting the same error.

**Comment by leokhachatorians** [comment]
I think the author made some breaking changes/abandoned this. If you guys want follow my fork and we can start removing a bunch of the fluff. https://github.com/leokhachatorians/DSDownload

**Comment by d6o** [comment]
Sorry for this.
I'm traveling, come home tomorrow night and throw a new version with this fix. Working on a better module to perform downloads.

**Comment by inferillum** [comment]
Sounds great. I'm looking forward for a fixed version.

**Comment by d6o** [comment]
Version 1.6.0.0 released with several improvements.
I did the tests in python2 and Python3 on OSX if someone can test on other platforms I'd be grateful to hear the feedback.

**Comment by inferillum** [comment]
After upgrading to 1.6.0.0, getting this error:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\Scripts\dsdownload-script.py", line 9, in <module>
    load_entry_point('DSDownload==1.6.0.0', 'console_scripts', 'dsdownload')()
  File "c:\users\username\appdata\local\programs\python\python35-32\lib\site-packages\DSDownload__init__.py", line 35, in main
    DSDownload(args.urls, args.workers, args.output)
TypeError: 'module' object is not callable

**Comment by d6o** [comment]
Made some minor changes to make it more compatible with Windows.
I have no machine with Windows 10, I did tests on Windows 8 and all went well.

If you can do a test I would be grateful to receive feedback

**Comment by inferillum** [comment]
I can confirm now that it works as intended. It would be great, however, if you could introduce some kind of a progression bar.

**Comment by d6o** [comment]
The new download module introduced in version 1.6.0.0 already allows you to create a progress bar and also the ability to resume downloads, these are my next goals for this project.

Thanks for the sugestion
